apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: frontend
        image: nginx:1.21:prod
        env:
        - name: API_URL
          value: http://backend:3000/prod
