apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fullstack-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/homee21634/GitOpsDemo.git
    targetRevision: HEAD
    path: apps/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/homee21634/GitOpsDemo.git
    targetRevision: HEAD
    path: apps/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
